### ISSUE TITLE
如何训练yolov3或者yolov4自定义数据集

### ISSUE THREAD

**Issue by 1zzc** [wuhanstudio/whitebox-adversarial-toolbox#2]
博主，你好
       如何使用这个项目中的yolov3或者yolov4网络，训练自定义数据集并攻击。
       感谢你的解答。

**Comment by wuhanstudio** [comment]
你好，这个 toolbox 专注于攻击已有模型，所以没有  YOLO 训练相关的代码。

另一个项目里，我包含了用自定义数据集训练 YOLO (v3, v4, tiny) 的全部代码，

https://github.com/wuhanstudio/adversarial-ros-detection

训练模型的文档：

https://github.com/wuhanstudio/adversarial-ros-detection/tree/master/doc
